### ISSUE TITLE
Provide link to npmjs.com and git repo

### ISSUE THREAD

**Issue by landau** [mrjoelkemp/packagestats-issues#1]
Lovely site. Quite handy. I'd like to be able to link directly to the package after viewing stats.

Linking to npmjs.com at a minimum would be great, but additionally linking to the package's ghub repo (or whatever SCM site) would be even better.

Cheers!

**Comment by mrjoelkemp** [comment]
Thanks, Trevor.

Great idea. I'll make the package name a link to its npm page and look into
getting the github repo url for the package from the npm api (if possible).

**Comment by mrjoelkemp** [comment]
Thanks again for the suggestion, @landau. I pushed it live.

**Comment by landau** [comment]
Nice! Looks good!
