### ISSUE TITLE
Missing title for `/:user/allTopPackages`

### ISSUE THREAD

**Issue by twolfson** [mrjoelkemp/packagestats-issues#2]
This is a non-important issue but I figured you should know. On the "View all top packages" packages page, there is no page title like the rest =(

Here's an example page: http://www.packagestats.io/twolfson/allTopPackages

![selection_209](https://cloud.githubusercontent.com/assets/902488/11947190/377c1d9e-a829-11e5-8e74-706b18cbf65f.png)

**Comment by mrjoelkemp** [comment]
Great catch! Thanks for reporting the issue. I missed that on a few pages.
